permalink: /:categories/:title.html
url: "http://deathscytheh.github.io/crowd/"
baseurl: "/crowd"
full_name: "Arkebit"
first_name: "Crowd"
last_name: "Aceptation"
blog_title: "Crowd Aceptation"
author_img_name_path: "/images/users/arkebit.jpg"
disqus_shortname: ""
copyright_year: "2014"
google_analytics_code: ""
aboutme: "Arkebit - Disruptive Solutions"
twitter: "deathscytheh"
github: "deathscytheh"
facebook: "deathscythe"
linkined_url: ""